// Builds frontend/assets/icons/icons.svg: one SVG "sprite" that holds only
// the Lucide icons Swatchfin uses. Run it with `npm run icons`.
//
// How it works, in plain English:
//   1. Read each icon file we need from the pinned lucide-static package.
//   2. Keep only the shapes inside it (the <path>, <circle> ... tags).
//   3. Wrap those shapes in a <symbol id="icon-name"> tag.
//   4. Save all symbols in one file, plus Lucide's licence next to it.
//
// The page then shows an icon with:
//   <svg class="sf-icon"><use href="assets/icons/icons.svg#search"/></svg>
// Stroke width, colour and line caps come from the .sf-icon CSS class, so
// every icon gets the same 1.75 stroke and follows the text colour.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// Add a name here when a page needs a new icon, then run `npm run icons`.
// Names match the files in node_modules/lucide-static/icons/.
const ICONS = [
  'app-window',
  'arrow-left',
  'arrow-right',
  'arrow-up-right',
  'badge-check',
  'braces',
  'calendar',
  'check',
  'chevron-down',
  'circle-alert',
  'circle-check',
  'circle-x',
  'code',
  'contrast',
  'copy',
  'download',
  'external-link',
  'file-text',
  'globe',
  'image',
  'info',
  'loader-circle',
  'megaphone',
  'menu',
  'message-square-quote',
  'message-square-text',
  'moon',
  'palette',
  'printer',
  'quote',
  'refresh-cw',
  'search',
  'shield-check',
  'sun',
  'swatch-book',
  'target',
  'triangle-alert',
  'type',
  'users',
  'wind',
  'x',
];

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const lucideDir = path.join(root, 'node_modules', 'lucide-static');
const outDir = path.join(root, 'frontend', 'assets', 'icons');

/**
 * Turns one Lucide icon file into a <symbol> tag.
 * @param {string} name Icon name, e.g. "search".
 * @returns {Promise<string>} The <symbol> markup.
 */
async function toSymbol(name) {
  const file = path.join(lucideDir, 'icons', `${name}.svg`);
  const svg = await readFile(file, 'utf8');

  // Every Lucide icon is drawn on a 24 x 24 grid. Stop if that ever changes,
  // because our CSS sizes (16/20/24 px) assume it.
  if (!svg.includes('viewBox="0 0 24 24"')) {
    throw new Error(`${name}: unexpected viewBox`);
  }

  // Grab what sits between the opening <svg ...> tag and the closing </svg>.
  const match = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!match) throw new Error(`${name}: could not read the SVG shapes`);

  // Put the shapes on one line to keep the sprite small.
  const shapes = match[1].replace(/\s*\n\s*/g, '').trim();
  return `<symbol id="${name}" viewBox="0 0 24 24">${shapes}</symbol>`;
}

async function main() {
  const pkg = JSON.parse(await readFile(path.join(lucideDir, 'package.json'), 'utf8'));
  const symbols = await Promise.all([...ICONS].sort().map(toSymbol));

  const sprite = [
    `<!-- Lucide icons v${pkg.version} (ISC licence, see LICENSE.txt). -->`,
    '<!-- Generated by tools/build-icons.mjs. Do not edit by hand. -->',
    '<svg xmlns="http://www.w3.org/2000/svg">',
    ...symbols,
    '</svg>',
    '',
  ].join('\n');

  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, 'icons.svg'), sprite);
  // The ISC licence asks us to keep Lucide's copyright notice with the icons.
  await writeFile(path.join(outDir, 'LICENSE.txt'), await readFile(path.join(lucideDir, 'LICENSE')));

  console.log(`icons.svg: ${symbols.length} icons from lucide-static v${pkg.version}`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
